language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t danutgita/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danutgita/docker-react npm run test
