language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t danutgita/docker-react -f Dockerfile.dev .

script:
  - docker run danutgita/docker-react npm run test -- --coverage 
